app_learning_logs/urls.py
"""Defines URL patterns for app_learning_logs."""
from django.urls import path

from . import views

app_name = "app_learning_logs"
urlpatterns = [
    # Home Page
    path("", views.index, name="index"),
    path("topics/", views.topics, name="topics"),
    path("topics/<int:topic_id>", views.topic, name="topic"),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_learning_logs.urls")),
]

app_learning_logs/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self) -> str:
        return "{}...".format(self.text[:50])

app_learning_logs/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.
def index(request):
    return render(request, "app_learning_logs/index.html")


def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by("date_added")
    context = {"topics": topics}
    return render(request, "app_learning_logs/topics.html", context)


def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "app_learning_logs/topic.html", context)

app_learning_logs/templates/app_learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
            shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'app_learning_logs:index' %}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>

    </main>
</body>

</html>

app_learning_logs/templates/app_learning_logs/index.html
{% extends "app_learning_logs/base.html" %}

{% block page_header %}

<div class="jumbotron">
    <h1 class="display-3">Track your learning.</h1>
    <p class="lead">Learning log helps you keep track of your learning, for any topic you're learning about.</p>
</div>

{% endblock page_header %}

app_learning_logs/templates/app_learning_logs/topic.html
{% extends "app_learning_logs/base.html" %}

{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}

{% for entry in entries %}
<div class="card mb-3">
    <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
    </h4>
    <div class="card-body">
        {{ entry.text|linebreaks }}
    </div>
</div>
{% empty %}
<li>There are no entries for this topic yet.</li>
{% endfor %}


{% endblock content %}

app_learning_logs/templates/app_learning_logs/topics.html
{% extends "app_learning_logs/base.html" %}

{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}

{% block content %}

<ul>
    {% for topic in topics %}
    <li>
        <h3>
            <a href="{% url 'app_learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>
    </li>
    {% empty %}
    <li>
        <h3>No topics have been added yet.</h3>
    </li>
    {% endfor %}
</ul>

{% endblock content %}